name: Deploy to Azure Web App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          cd backend
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest flake8
      - name: Run Linter
        run: |
          cd backend
          source venv/bin/activate
          flake8 --max-line-length=120 --exclude=venv .
      - name: Run Tests
        run: |
          cd backend
          source venv/bin/activate
          pytest tests || echo "No tests found, skipping..."
  build-and-deploy:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          cd backend
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
      - name: Log in to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

<<<<<<< HEAD
      - name: Zip backend for deployment
=======
      - name: **Cleanup unnecessary files before deployment**
>>>>>>> 817e461 (Fix deployment issue by removing .pytest_cache and .gitignore)
        run: |
          cd backend
          echo "Removing unnecessary files..."
          rm -rf .pytest_cache .gitignore .env
<<<<<<< HEAD
          zip -r ../backend.zip .
=======
          find . -type d -name '__pycache__' -exec rm -rf {} +
          find . -type d -name '.pytest_cache' -exec rm -rf {} +
          find . -type f -name '.gitignore' -exec rm -f {} +
          ls -al  # Sprawdźmy, czy pliki na pewno zostały usunięte

      - name: **Prepare backend for deployment**
        run: |
          cd backend
          zip -r ../backend.zip . --exclude=venv/* --exclude=node_modules/* --exclude=.pytest_cache/* --exclude=.gitignore

>>>>>>> 817e461 (Fix deployment issue by removing .pytest_cache and .gitignore)
      - name: Deploy Backend to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: backend.zip

<<<<<<< HEAD
=======
      - name: **Set SCM_DO_BUILD_DURING_DEPLOYMENT to avoid Kudu Sync issues**
        uses: azure/appservice-settings@v1
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          settings: |
            [
              {
                "name": "SCM_DO_BUILD_DURING_DEPLOYMENT",
                "value": "true",
                "slotSetting": false
              }
            ]

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

>>>>>>> 817e461 (Fix deployment issue by removing .pytest_cache and .gitignore)
      - name: Build frontend
        run: |
          cd frontend
          npm install
          npm run build
          cd dist
          zip -r ../../frontend.zip .
      - name: Create $web container if it doesn't exist
        uses: azure/CLI@v1
        with:
          azcliversion: latest
          inlineScript: |
            az storage container create --account-name ${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }} --account-key ${{ secrets.AZURE_STORAGE_ACCOUNT_KEY }} --name '$web' --public-access blob || true
      - name: Upload frontend to Azure Blob Storage
        uses: azure/CLI@v1
        with:
          azcliversion: latest
          inlineScript: |
            az storage blob upload-batch --account-name ${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }} --account-key ${{ secrets.AZURE_STORAGE_ACCOUNT_KEY }} --destination \$web --source frontend/dist --overwrite
