name: Deploy to Azure Static Web Apps

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Deploy to Azure Static Web Apps
        id: deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "frontend"  # Katalog z kodem frontendu (np. React, Vue)
          api_location: "backend"  # MUSI być funkcją Azure Functions
          output_location: "frontend/dist"  # Folder zbudowanego frontendu (np. React)

      - name: Debug deployment
        run: echo "Deployment status: ${{ steps.deploy.outcome }}"
