name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies & build frontend
        run: |
          cd frontend
          npm install
          npm run build
          ls -la dist

      - name: Debug - check frontend dist
        run: |
          if [ -d frontend/dist ]; then echo "dist folder exists"; else echo "dist folder is missing"; exit 1; fi

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies & build backend
        run: |
          cd backend
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
          ls -la venv/bin/

      - name: Debug - check if venv/bin/python exists
        run: |
          if [ -f backend/venv/bin/python ]; then echo "venv/bin/python exists"; else echo "venv/bin/python is missing"; exit 1; fi

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "frontend"
          api_location: "backend"
          output_location: "dist"