name: Deploy to Azure Static Web Apps

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install dependencies & build frontend
        run: |
          cd frontend
          npm install
          npm run build
          mkdir -p dist  # Upewnij się, że folder dist istnieje
          ls -la dist

      - name: Debug - check frontend dist
        run: |
          if [ -d frontend/dist ]; then echo "dist folder exists"; else echo "dist folder is missing"; exit 1; fi

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "frontend"
          output_location: "dist"

  deploy-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Cleanup old deployment files
        run: |
          rm -rf backend/.venv
          rm -rf backend/__pycache__
          echo "Removed cached files before deployment"

      - name: Install dependencies & build backend
        run: |
          cd backend
          python -m venv venv
          source venv/bin/activate || . venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt || { echo "Error installing dependencies"; exit 1; }
          deactivate

      - name: Debug - check venv existence
        run: |
          if [ ! -f backend/venv/bin/python ] && [ ! -f backend/venv/Scripts/python.exe ]; then 
              echo "venv not created properly!"; 
              exit 1; 
          fi

      - name: Package Backend for Deployment
        run: |
          cd backend
          zip -r backend.zip . -x "*.git*" "*.venv*" "__pycache__/*"

      - name: Deploy Backend to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: "my-marketplace-api"
          slot-name: "production"
          package: "backend/backend.zip"
